//===========================================================================
//
// Name:				chars.c
// Function:		characteristics for ensign
// Programmer:		Blair Williams
// Last update:	1999-04-10
// Tab Size:		3 (real tabs)
//===========================================================================

#include "chars.h"

character "ensign"
{
	CHARACTERISTIC_NAME				"ensign"
	CHARACTERISTIC_ALT_NAME				"ensign"
	CHARACTERISTIC_GENDER				"female"
	CHARACTERISTIC_ATTACK_SKILL			0.4
	CHARACTERISTIC_WEAPONWEIGHTS			"bots/mean_w.c"
//	CHARACTERISTIC_WEAPONWEIGHTS			"bots/ensign_w.c"
	CHARACTERISTIC_WEAPONSWITCHER			0.4
	CHARACTERISTIC_AIM_SKILL			0.4
	CHARACTERISTIC_AIM_ACCURACY			0.4
	CHARACTERISTIC_VIEW_ACCELERATION		300
	CHARACTERISTIC_VIEW_DEACCELERATION		300
	CHARACTERISTIC_REACTIONTIME			1.3
	//
	CHARACTERISTIC_CHAT_FILE			"bots/ensign_t.c"
	CHARACTERISTIC_CHAT_NAME			"ensign"
	CHARACTERISTIC_CHAT_CPM				400
	CHARACTERISTIC_CHAT_REPLY			0.65
	CHARACTERISTIC_CHAT_DEATH			0.95
	CHARACTERISTIC_CHAT_ENTEREXITGAME		0.95
	CHARACTERISTIC_CHAT_INSULT			0.95
	CHARACTERISTIC_CHAT_KILL			0.95
	CHARACTERISTIC_CHAT_MISC			0.95
	CHARACTERISTIC_CHAT_STARTENDLEVEL		0.95
	CHARACTERISTIC_CHAT_RANDOM			0.55
	//
	CHARACTERISTIC_CROUCHER				0.6
	CHARACTERISTIC_JUMPER				0.4
	CHARACTERISTIC_WEAPONJUMPING			0.4
	CHARACTERISTIC_GRAPPLE_USER			0.4
	//
	CHARACTERISTIC_ITEMWEIGHTS			"bots/items_i.c"
//	CHARACTERISTIC_ITEMWEIGHTS			"bots/ensign_i.c"
	CHARACTERISTIC_HEALTHGATHERER			0.4
	CHARACTERISTIC_ARMORGATHERER			0.4
	CHARACTERISTIC_TELEFRAGAWARE			0.4
	CHARACTERISTIC_AGGRESSION			0.4
	CHARACTERISTIC_FEAR				0.6
	CHARACTERISTIC_SELFPRESERVATION			0.4
	CHARACTERISTIC_VENGEFULNESS			0.4
	CHARACTERISTIC_CAMPER				0.6
	CHARACTERISTIC_EGO				1
	//
	CHARACTERISTIC_FAVCLASS				0
	CHARACTERISTIC_SKIN_SWITCHER			0.9
	CHARACTERISTIC_NAME_SWITCHER			0.8
	CHARACTERISTIC_FRUSTRATEDTEEN			0
	CHARACTERISTIC_FRUSTRATEDNESS			0.6
	CHARACTERISTIC_EASY_FRAGGER			0.4
	CHARACTERISTIC_ALERTNESS			0.4
	CHARACTERISTIC_SOUNDTYPE			1
	CHARACTERISTIC_3DACCELERATOR			1
	CHARACTERISTIC_CONTROLTYPE			1
	CHARACTERISTIC_TEAMSPIRIT			1
	CHARACTERISTIC_PIZZAPREFERENCE			0.01
	CHARACTERISTIC_CALL_PRONE			0
	CHARACTERISTIC_BEDDY_BYE_TIME			0
	CHARACTERISTIC_EYE_COR_DEVICE			0
	CHARACTERISTIC_GAMMA_CORRECTION			0
	CHARACTERISTIC_BUTTKISSER			0
} //end character ensign


