//===========================================================================
//
// Name:				ernie_c.c
// Function:		characteristics for Evil Ernie
// Programmer:		Felix 
// Last update:	1999-04-05
// Tab Size:		3 (real tabs)
//===========================================================================

#include "chars.h"

character "ernie"
{
	CHARACTERISTIC_NAME				"Evil Ernie"
	CHARACTERISTIC_ALT_NAME				"Ernie"
	CHARACTERISTIC_GENDER				"male"
	CHARACTERISTIC_ATTACK_SKILL			0.80
	CHARACTERISTIC_WEAPONWEIGHTS			"bots/mean_w.c"
//	CHARACTERISTIC_WEAPONWEIGHTS			"bots/ernie_w.c"
	CHARACTERISTIC_WEAPONSWITCHER			0.5
	CHARACTERISTIC_AIM_SKILL			0.7
	CHARACTERISTIC_AIM_ACCURACY			0.7
	CHARACTERISTIC_VIEW_ACCELERATION		300
	CHARACTERISTIC_VIEW_DEACCELERATION		300
	CHARACTERISTIC_REACTIONTIME			1
	//
	CHARACTERISTIC_CHAT_FILE			"bots/ernie_t.c"
	CHARACTERISTIC_CHAT_NAME			"Ernie"
	CHARACTERISTIC_CHAT_CPM				400
	CHARACTERISTIC_CHAT_REPLY			0.77
	CHARACTERISTIC_CHAT_DEATH			0.80
	CHARACTERISTIC_CHAT_ENTEREXITGAME		0.6
	CHARACTERISTIC_CHAT_INSULT			0.65
	CHARACTERISTIC_CHAT_KILL			0.85
	CHARACTERISTIC_CHAT_MISC			0.75
	CHARACTERISTIC_CHAT_STARTENDLEVEL		0.7
	CHARACTERISTIC_CHAT_RANDOM			0.65
	//
	CHARACTERISTIC_CROUCHER				0.01
	CHARACTERISTIC_JUMPER				0.75
	CHARACTERISTIC_WEAPONJUMPING			0.88
	CHARACTERISTIC_GRAPPLE_USER			0.88
	//
	CHARACTERISTIC_ITEMWEIGHTS			"bots/items_i.c"
//	CHARACTERISTIC_ITEMWEIGHTS			"bots/ernie_i.c"
	CHARACTERISTIC_HEALTHGATHERER			0.35
	CHARACTERISTIC_ARMORGATHERER			0.35
	CHARACTERISTIC_TELEFRAGAWARE			0.35
	CHARACTERISTIC_AGGRESSION			0.9
	CHARACTERISTIC_FEAR				0.25
	CHARACTERISTIC_SELFPRESERVATION			0.55
	CHARACTERISTIC_VENGEFULNESS			0.97
	CHARACTERISTIC_CAMPER				0.66
	CHARACTERISTIC_EGO				0.8
	//
	CHARACTERISTIC_FAVCLASS				0
	CHARACTERISTIC_SKIN_SWITCHER			0.8
	CHARACTERISTIC_NAME_SWITCHER			0.01
	CHARACTERISTIC_FRUSTRATEDTEEN			0
	CHARACTERISTIC_FRUSTRATEDNESS			0.05
	CHARACTERISTIC_EASY_FRAGGER			0.7
	CHARACTERISTIC_ALERTNESS			0.45
	CHARACTERISTIC_SOUNDTYPE			1
	CHARACTERISTIC_3DACCELERATOR			1
	CHARACTERISTIC_CONTROLTYPE			1
	CHARACTERISTIC_TEAMSPIRIT			1
	CHARACTERISTIC_PIZZAPREFERENCE			0.01
	CHARACTERISTIC_CALL_PRONE			0.1
	CHARACTERISTIC_BEDDY_BYE_TIME			0.1
	CHARACTERISTIC_EYE_COR_DEVICE			0
	CHARACTERISTIC_GAMMA_CORRECTION			0
	CHARACTERISTIC_BUTTKISSER			0
} //end character Ernie


