//===========================================================================
//
// Name:				chars.c
// Function:		characteristics for razor
// Programmer:		Blair Williams
// Last update:	1999-04-10
// Tab Size:		3 (real tabs)
//===========================================================================

#include "chars.h"

character "razor"
{
	CHARACTERISTIC_NAME				"razor"
	CHARACTERISTIC_ALT_NAME				"razor"
	CHARACTERISTIC_GENDER				"male"
	CHARACTERISTIC_ATTACK_SKILL			0.30
	CHARACTERISTIC_WEAPONWEIGHTS			"bots/mean_w.c"
//	CHARACTERISTIC_WEAPONWEIGHTS			"bots/razor_w.c"
	CHARACTERISTIC_WEAPONSWITCHER			0.3
	CHARACTERISTIC_AIM_SKILL			0.3
	CHARACTERISTIC_AIM_ACCURACY			0.3
	CHARACTERISTIC_VIEW_ACCELERATION		300
	CHARACTERISTIC_VIEW_DEACCELERATION		300
	CHARACTERISTIC_REACTIONTIME			1.3
	//
	CHARACTERISTIC_CHAT_FILE			"bots/razor_t.c"
	CHARACTERISTIC_CHAT_NAME			"razor"
	CHARACTERISTIC_CHAT_CPM				400
	CHARACTERISTIC_CHAT_REPLY			0.65
	CHARACTERISTIC_CHAT_DEATH			0.95
	CHARACTERISTIC_CHAT_ENTEREXITGAME		0.95
	CHARACTERISTIC_CHAT_INSULT			0.95
	CHARACTERISTIC_CHAT_KILL			0.95
	CHARACTERISTIC_CHAT_MISC			0.95
	CHARACTERISTIC_CHAT_STARTENDLEVEL		0.95
	CHARACTERISTIC_CHAT_RANDOM			0.55
	//
	CHARACTERISTIC_CROUCHER				0.7
	CHARACTERISTIC_JUMPER				0.3
	CHARACTERISTIC_WEAPONJUMPING			0.3
	CHARACTERISTIC_GRAPPLE_USER			0.3
	//
	CHARACTERISTIC_ITEMWEIGHTS			"bots/items_i.c"
//	CHARACTERISTIC_ITEMWEIGHTS			"bots/razor_i.c"
	CHARACTERISTIC_HEALTHGATHERER			0.3
	CHARACTERISTIC_ARMORGATHERER			0.3
	CHARACTERISTIC_TELEFRAGAWARE			0.3
	CHARACTERISTIC_AGGRESSION			0.3
	CHARACTERISTIC_FEAR				0.7
	CHARACTERISTIC_SELFPRESERVATION			0.3
	CHARACTERISTIC_VENGEFULNESS			0.3
	CHARACTERISTIC_CAMPER				0.7
	CHARACTERISTIC_EGO				1
	//
	CHARACTERISTIC_FAVCLASS				0
	CHARACTERISTIC_SKIN_SWITCHER			0.9
	CHARACTERISTIC_NAME_SWITCHER			0.8
	CHARACTERISTIC_FRUSTRATEDTEEN			0
	CHARACTERISTIC_FRUSTRATEDNESS			0.70
	CHARACTERISTIC_EASY_FRAGGER			0.3
	CHARACTERISTIC_ALERTNESS			0.3
	CHARACTERISTIC_SOUNDTYPE			1
	CHARACTERISTIC_3DACCELERATOR			1
	CHARACTERISTIC_CONTROLTYPE			1
	CHARACTERISTIC_TEAMSPIRIT			1
	CHARACTERISTIC_PIZZAPREFERENCE			0.01
	CHARACTERISTIC_CALL_PRONE			0
	CHARACTERISTIC_BEDDY_BYE_TIME			0
	CHARACTERISTIC_EYE_COR_DEVICE			0
	CHARACTERISTIC_GAMMA_CORRECTION			0
	CHARACTERISTIC_BUTTKISSER			0
} //end character razor


