//        SWARM

#include "chars.h"

character "Swarm"
{
	CHARACTERISTIC_NAME						"Swarm"
	CHARACTERISTIC_ALT_NAME					"Swarm"
	CHARACTERISTIC_GENDER					"Male"
	CHARACTERISTIC_ATTACK_SKILL			1
	CHARACTERISTIC_WEAPONWEIGHTS			"bots/Swarm_w.c"
	CHARACTERISTIC_WEAPONSWITCHER			0.5
	CHARACTERISTIC_AIM_SKILL				1
	CHARACTERISTIC_AIM_ACCURACY			1
	CHARACTERISTIC_VIEW_ACCELERATION		900//degrees per second, maximum 1800
	CHARACTERISTIC_VIEW_DEACCELERATION	900
	CHARACTERISTIC_REACTIONTIME			0
	//
	CHARACTERISTIC_CROUCHER					0.3
	CHARACTERISTIC_JUMPER					0.75
	CHARACTERISTIC_WEAPONJUMPING			0.85
	CHARACTERISTIC_GRAPPLE_USER			1
	//
   	//
	CHARACTERISTIC_CHAT_FILE			"bots/Swarm_t.c"
	CHARACTERISTIC_CHAT_NAME			"Swarm"
	CHARACTERISTIC_CHAT_CPM				400
	CHARACTERISTIC_CHAT_REPLY			1
	CHARACTERISTIC_CHAT_DEATH			1
	CHARACTERISTIC_CHAT_ENTEREXITGAME		1
	CHARACTERISTIC_CHAT_INSULT			1
	CHARACTERISTIC_CHAT_KILL			1
	CHARACTERISTIC_CHAT_MISC			1
	CHARACTERISTIC_CHAT_STARTENDLEVEL		1
	CHARACTERISTIC_CHAT_RANDOM			0.75
	//
	CHARACTERISTIC_ITEMWEIGHTS				"bots/items_i.c"
//	CHARACTERISTIC_ITEMWEIGHTS				"bots/Swarm_i.c"
	CHARACTERISTIC_HEALTHGATHERER			0.75
	CHARACTERISTIC_ARMORGATHERER			0.75
	CHARACTERISTIC_TELEFRAGAWARE			0.45
	CHARACTERISTIC_AGGRESSION				1
	CHARACTERISTIC_FEAR						0.01
	CHARACTERISTIC_SELFPRESERVATION		0.75
	CHARACTERISTIC_VENGEFULNESS			1
	CHARACTERISTIC_CAMPER					0.01
	CHARACTERISTIC_EGO						0.8
	//
	CHARACTERISTIC_FAVCLASS					0
	CHARACTERISTIC_SKIN_SWITCHER			0
	CHARACTERISTIC_NAME_SWITCHER			0
	CHARACTERISTIC_FRUSTRATEDTEEN			0
	CHARACTERISTIC_FRUSTRATEDNESS			0
	CHARACTERISTIC_EASY_FRAGGER			0
	CHARACTERISTIC_ALERTNESS				1
	CHARACTERISTIC_SOUNDTYPE				2
	CHARACTERISTIC_3DACCELERATOR			1
	CHARACTERISTIC_CONTROLTYPE				2
	CHARACTERISTIC_TEAMSPIRIT				0.6
	CHARACTERISTIC_PIZZAPREFERENCE		0
	CHARACTERISTIC_CALL_PRONE				0.5
	CHARACTERISTIC_BEDDY_BYE_TIME			0.01
	CHARACTERISTIC_EYE_COR_DEVICE			0
	CHARACTERISTIC_GAMMA_CORRECTION		0.6
	CHARACTERISTIC_BUTTKISSER				0
} //end character
